import { defaultSchema, Schema } from "hast-util-sanitize";

export const customSchema: Schema = {
  ...defaultSchema,
  tagNames: [
    ...(defaultSchema.tagNames || []),
    "div",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "ul",
    "ol",
    "li",
    "p",
    "br",
    "strong",
    "em",
    "blockquote",
    "code",
    "pre",
    "hr",
    "a",
    "img",
    "table",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
    "span",
    "iframe",
  ],
  attributes: {
    ...defaultSchema.attributes,
    a: ["href", "name", "target", "rel", "title"],
    code: ["className"],
    div: ["className"],
    img: [
      "src",
      "alt",
      "title",
      "width",
      "height",
      "className",
      "loading",
      "decoding",
      "referrerpolicy",
    ],
    iframe: [
      "src",
      "width",
      "height",
      "title",
      "allow",
      "allowfullscreen",
      "frameborder",
      "loading",
      "sandbox",
      "referrerpolicy",
    ],
    pre: ["className"],
    span: ["className"],
  },
  protocols: {
    ...defaultSchema.protocols,
    href: ["http", "https", "mailto", "tel"],
    src: ["http", "https"],
  },
  clobberPrefix: "user-content-",
  allowComments: false,
};
